version: '3.8'

services:
  mindmap-app:
    build: .
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mindmap.rule=Host(`mindmap.localhost`)"
      - "traefik.http.services.mindmap.loadbalancer.server.port=80"
